{{ if not .Values.features.sse.disabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameSSE" "appNameSuffix" "") -}}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.sse.autoscaling) -}}
{{ include "ocis.hpa" . }}
{{ end }}
