{{ $name := (include "app-template.serviceAccountName" .)}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ $name }}"
rules: {{ .Values.serviceAccount.roleRules | toYaml | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ $name }}"
roleRef:
  kind: Role
  name: "{{ $name }}"
  apiGroup: rbac.authorization.k8s.io
