---
image:
  # https://github.com/MacroPower/osrs_ge_exporter
  repository: macropower/osrs_ge_exporter
  tag: v0.3
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 8080
        protocol: TCP

serviceMonitor:
  main:
    enabled: false
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
