---
image:
  # https://github.com/MacroPower/osrs_ge_exporter
  repository: macropower/osrs_ge_exporter
  tag: v0.3
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 8080
        protocol: TCP

serviceMonitor:
  main:
    enabled: false
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s

prometheusRule:
  main:
    enabled: false
    groups:
      - name: osrs-ge-exporter.rules
        rules:
          - record: :osrs_ge_ha_profit:sum
            expr: |-
              sum(
                (osrs_ge_item_limit * ((osrs_ge_item_high_alch - osrs_ge_item_low_latest) > 1000))
                and
                (osrs_ge_item_low_volume_5m > 15)
              )
