{{- if and .Values.httpRoute.enabled .Values.onlyoffice.collaboration.enabled .Values.onlyoffice.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-collaboration-httproute
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: collaboration
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      sectionName: {{ .Values.httpRoute.gateway.sectionName | default "collaboration-https" }}
  hostnames:
    - {{ .Values.global.domain.wopi | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "opencloud.fullname" . }}-collaboration
          port: 9300
{{- end }}
