{{- if and .Values.httpRoute.enabled .Values.collabora.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-collabora-httproute
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: collabora
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      sectionName: {{ .Values.httpRoute.gateway.sectionName | default "collabora-https" }}
  hostnames:
    - {{ .Values.global.domain.collabora | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "opencloud.fullname" . }}-collabora
          port: 9980
{{- end }}
