{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-httproute
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      sectionName: {{ .Values.httpRoute.gateway.sectionName | default "opencloud-https" }}
  hostnames:
    - {{ include "opencloud.domain" . | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            remove:
              - "Permissions-Policy"
      backendRefs:
        - name: {{ include "opencloud.opencloud.fullname" . }}
          port: 9200
{{- end }}
