{{- if and .Values.httpRoute.enabled (eq .Values.opencloud.storage.mode "s3") .Values.opencloud.storage.s3.internal.enabled .Values.opencloud.storage.s3.internal.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-minio-httproute
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      sectionName: {{ .Values.httpRoute.gateway.sectionName | default "minio-https" }}
  hostnames:
    - {{ include "opencloud.minio.domain" . | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "opencloud.minio.fullname" . }}
          port: 9001
{{- end }}
