{{- if and .Values.httpRoute.enabled .Values.onlyoffice.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice-httproute
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
      sectionName: {{ .Values.httpRoute.gateway.sectionName | default "onlyoffice-https" }}
  hostnames:
    - {{ .Values.global.domain.onlyoffice | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        {{- if eq .Values.httpRoute.gateway.className "traefik" }}
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: add-x-forwarded-proto-https
        {{- else }}
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
        {{- end }}
      backendRefs:
        - name: {{ include "opencloud.fullname" . }}-onlyoffice
          port: 80
{{- end }}
