{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "opencloud.fullname" . }}-reference-grant
  namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Release.Namespace }}
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.httpRoute.gateway.name }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "opencloud.fullname" . }}-cert-reference-grant
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Values.httpRoute.gateway.namespace | default .Release.Namespace }}
  to:
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-opencloud-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-opencloud-minio-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-keycloak-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-collabora-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-collaboration-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-wopi-tls
{{- end }}
