{{- if and .Values.httpRoute.enabled .Values.httpRoute.gateway.create (eq .Values.httpRoute.gateway.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-x-forwarded-proto-https
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
{{- end }}
