---
{{- include "bjw-s.common.loader.init" . }}

{{- define "template.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

{{ if not .Values.command }}
command: /bin/sh
{{ end }}
{{ if not .Values.args }}
args: [-c, /init.sh]
{{ end }}

{{ if not .Values.configMaps.init }}
configMaps:
  init:
    enabled: true
    data:
      init.sh: |
        {{- .Values.init | nindent 8 }}
{{ end }}

{{ if not .Values.persistence.init }}
persistence:
  init:
    enabled: true
    name: "{{ .Release.Name }}-init"
    type: configMap
    defaultMode: "0777"
    subPath:
      - path: init.sh
        mountPath: /init.sh
        readOnly: true
{{ end }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "template.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
