{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rclone.serviceAccountName" . }}
  labels:
{{ include "rclone.labels" . | indent 4 }}
{{- end -}}
