{{ if .Values.features.appsIntegration.enabled }}
{{- range $officeSuite := .Values.features.appsIntegration.wopiIntegration.officeSuites }}
{{ if and $officeSuite.enabled $officeSuite.ingress.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" $ "appName" "appNameCollaboration" "appNameSuffix" (regexReplaceAll "\\W+" (lower $officeSuite.name) "-")) -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
{{ include "ocis.metadata" $ }}
{{- if $officeSuite.ingress.labels }}
{{ toYaml $officeSuite.ingress.labels | indent 4 }}
{{- end }}
  {{- if $officeSuite.ingress.annotations }}
  annotations:
    {{- range $key, $value := $officeSuite.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if $officeSuite.ingress.ingressClassName }}
  ingressClassName: {{ $officeSuite.ingress.ingressClassName }}
  {{- end }}
{{- if $officeSuite.ingress.tls }}
  tls:
{{ tpl (toYaml $officeSuite.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
    - host: {{ $officeSuite.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.appName | quote }}
                port:
                  number: 9300
{{ end }}
{{ end }}
{{ end }}
