{{ if .Values.features.appsIntegration.enabled }}
{{- range $officeSuite := .Values.features.appsIntegration.wopiIntegration.officeSuites }}
{{ if $officeSuite.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" $ "appName" "appNameCollaboration" "appNameSuffix" (regexReplaceAll "\\W+" (lower $officeSuite.name) "-")) -}}
---
{{ include "ocis.pdb" $ }}
{{ end }}
{{ end }}
{{ end }}
