{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameAudit" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" $ | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["audit", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}
            {{- include "ocis.events" . | nindent 12 }}

            - name: AUDIT_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: AUDIT_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: AUDIT_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            # Tracing not yet implemented: https://github.com/owncloud/ocis/issues/6172
            # - name: AUDIT_TRACING_ENABLED
            #   value: "{{ .Values.tracing.enabled }}"
            # - name: AUDIT_TRACING_TYPE
            #   value: {{ .Values.tracing.type | quote }}
            # - name: AUDIT_TRACING_ENDPOINT
            #   value: {{ .Values.tracing.endpoint | quote }}
            # - name: AUDIT_TRACING_COLLECTOR
            #   value: {{ .Values.tracing.collector | quote }}

            - name: AUDIT_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}
            - name: AUDIT_DEBUG_ADDR
              value: 0.0.0.0:9229

            - name: AUDIT_LOG_TO_CONSOLE
              value: "true"

            {{- include "ocis.caEnv" $ | nindent 12}}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: metrics-debug
              containerPort: 9229

          volumeMounts:
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true
            {{- include "ocis.caPath" $ | nindent 12}}

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ include "secrets.messagingSystemCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        {{- include "ocis.caVolume" $ | nindent 8}}
