{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "servarr.serviceAccountName" . }}
  labels:
{{ include "servarr.labels" . | indent 4 }}
{{- end -}}
