apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}
  labels:
{{ include "servarr.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "servarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servarr.fullname" . }}-metrics
  labels:
{{ include "servarr.labels" . | indent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "servarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
