{{ if .Values.features.appsIntegration.enabled }}
{{- range $officeSuite := .Values.features.appsIntegration.wopiIntegration.officeSuites }}
{{ if $officeSuite.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" $ "appName" "appNameAppProvider" "appNameSuffix" (regexReplaceAll "\\W+" (lower $officeSuite.name) "-")) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.appName }}
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    app: {{ $.appName }}
    ocis-metrics: enabled
    {{- include "ocis.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $.appName }}
  ports:
    - name: grpc
      port: 9164
      protocol: TCP
      appProtocol: {{ $.Values.service.appProtocol.grpc | quote}}
    - name: metrics-debug
      port: 9165
      protocol: TCP
      appProtocol: {{ $.Values.service.appProtocol.http | quote}}
{{ end }}
{{ end }}
{{ end }}
