{{ if .Values.features.virusscan.enabled }}
{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameAntivirus" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" $ | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["antivirus", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}
            {{- include "ocis.events" . | nindent 12 }}

            - name: ANTIVIRUS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: ANTIVIRUS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: ANTIVIRUS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}
            - name: ANTIVIRUS_DEBUG_ADDR
              value: 0.0.0.0:9277
            - name: ANTIVIRUS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            # Tracing not yet implemented: https://github.com/owncloud/ocis/issues/6171
            # - name: ANTIVIRUS_TRACING_ENABLED
            #   value: "{{ .Values.tracing.enabled }}"
            # - name: ANTIVIRUS_TRACING_TYPE
            #   value: {{ .Values.tracing.type | quote }}
            # - name: ANTIVIRUS_TRACING_ENDPOINT
            #   value: {{ .Values.tracing.endpoint | quote }}
            # - name: ANTIVIRUS_TRACING_COLLECTOR
            #   value: {{ .Values.tracing.collector | quote }}

            - name: ANTIVIRUS_INFECTED_FILE_HANDLING
              value: {{ .Values.features.virusscan.infectedFileHandling | quote }}
            - name: ANTIVIRUS_SCANNER_TYPE
              value: "icap"
            - name: ANTIVIRUS_ICAP_SCAN_TIMEOUT
              value: {{ .Values.features.virusscan.icap.timeout | quote }}
            - name: ANTIVIRUS_ICAP_URL
              value: {{ .Values.features.virusscan.icap.url | quote }}
            - name: ANTIVIRUS_ICAP_SERVICE
              value: {{ .Values.features.virusscan.icap.service | quote }}
            - name: ANTIVIRUS_MAX_SCAN_SIZE
              value: {{ .Values.features.virusscan.maxScanSize | quote }}
            - name: ANTIVIRUS_WORKERS
              value: {{ .Values.services.antivirus.events.consumer.concurrency | quote }}

            {{- include "ocis.caEnv" $ | nindent 12}}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: metrics-debug
              containerPort: 9277

          volumeMounts:
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true
            {{- include "ocis.caPath" $ | nindent 12}}

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ include "secrets.messagingSystemCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        {{- include "ocis.caVolume" $ | nindent 8}}
{{ end }}
