{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameSharing" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" .Values.services.sharing | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["sharing", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}
            {{- include "ocis.events" . | nindent 12 }}

            - name: SHARING_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: SHARING_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: SHARING_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: SHARING_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: SHARING_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: SHARING_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: SHARING_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: SHARING_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: SHARING_GRPC_ADDR
              value: 0.0.0.0:9150
            - name: SHARING_DEBUG_ADDR
              value: 0.0.0.0:9151

            - name: SHARING_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.jwtSecret" . }}
                  key: jwt-secret

            - name: SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD
              value: {{ .Values.features.sharing.publiclink.writeableShareMustHavePassword | quote }}

            - name: SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD
              value: {{ .Values.features.sharing.publiclink.shareMustHavePassword | quote }}

            # password policies
            - name: SHARING_PASSWORD_POLICY_MIN_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minCharacters | quote }}
            - name: SHARING_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minLowerCharacters | quote }}
            - name: SHARING_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minUpperCharacters | quote }}
            - name: SHARING_PASSWORD_POLICY_MIN_DIGITS
              value: {{ .Values.features.sharing.passwordPolicies.minDigits | quote }}
            - name: SHARING_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS
              value: {{ .Values.features.sharing.passwordPolicies.minSpecialCharacters | quote }}
            - name: SHARING_PASSWORD_POLICY_BANNED_PASSWORDS_LIST
              value: /etc/ocis/sharing-banned-passwords.txt

            # user sharing
            - name: SHARING_USER_DRIVER
              value: jsoncs3
            - name: SHARING_USER_JSONCS3_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: api-key
            - name: SHARING_USER_JSONCS3_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: user-id

            # public sharing
            - name: SHARING_PUBLIC_DRIVER
              value: jsoncs3
            - name: SHARING_PUBLIC_JSONCS3_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: api-key
            - name: SHARING_PUBLIC_JSONCS3_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "secrets.storageSystemSecret" . }}
                  key: user-id

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9150
            - name: metrics-debug
              containerPort: 9151

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true
            - name: configs
              mountPath: /etc/ocis

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: ocis-config-tmp
          emptyDir: {}
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ include "secrets.messagingSystemCASecret" . }}
          {{ else }}
          emptyDir: {}
          {{ end }}
        - name: configs
          configMap:
            name: sharing-banned-passwords-{{ .appName }}
