{{- if and (eq .Values.opencloud.storage.mode "s3") .Values.opencloud.storage.s3.internal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.minio.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opencloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "opencloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-minio-bucket
          image: {{ include "opencloud.image" (dict "imageValues" .Values.busybox.image "global" .Values.global) | quote }}
          imagePullPolicy: {{ include "opencloud.image.pullPolicy" (dict "pullPolicy" .Values.busybox.image.pullPolicy "global" .Values.global) | quote }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          command: ['sh', '-c', 'mkdir -p /data/{{ .Values.opencloud.storage.s3.internal.bucketName }}']
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: minio
          image: {{ include "opencloud.image" (dict "imageValues" .Values.opencloud.storage.s3.internal.image "global" .Values.global) | quote }}
          imagePullPolicy: {{ include "opencloud.image.pullPolicy" (dict "pullPolicy" .Values.opencloud.storage.s3.internal.image.pullPolicy "global" .Values.global) }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          args: ["server", "--console-address", ":9001", "/data"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{- if .Values.opencloud.storage.s3.internal.existingSecret }}
                          {{ .Values.opencloud.storage.s3.internal.existingSecret }}
                        {{- else }}
                          {{ include "opencloud.minio.fullname" . }}
                        {{- end }}
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{- if .Values.opencloud.storage.s3.internal.existingSecret }}
                          {{ .Values.opencloud.storage.s3.internal.existingSecret }}
                        {{- else }}
                          {{ include "opencloud.minio.fullname" . }}
                        {{- end }}
                  key: rootPassword
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /data
          startupProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            periodSeconds: 2
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            # Increased period to check less frequently
            periodSeconds: 60
            # Increased timeout to allow more time for response
            timeoutSeconds: 20
            # Increased failure threshold to be more tolerant
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            # Increased period to check less frequently
            periodSeconds: 30
            # Increased timeout to allow more time for response
            timeoutSeconds: 10
            # Increased failure threshold to be more tolerant
            failureThreshold: 5
          resources:
            {{- toYaml .Values.opencloud.storage.s3.internal.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.opencloud.storage.s3.internal.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.opencloud.storage.s3.internal.persistence.existingClaim }}
            claimName: {{ .Values.opencloud.storage.s3.internal.persistence.existingClaim | quote }}
            {{- else }}
            claimName: {{ include "opencloud.minio.fullname" . }}-data
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
