{{- if and .Values.opencloud.enabled .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.fullname" . }}-tika
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opencloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: tika
  template:
    metadata:
      labels:
        {{- include "opencloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: tika
    spec:
      containers:
        - name: tika
          image: {{ include "opencloud.image" (dict "imageValues" .Values.tika.image "global" .Values.global) | quote }}
          imagePullPolicy: {{ include "opencloud.image.pullPolicy" (dict "pullPolicy" .Values.tika.image.pullPolicy "global" .Values.global) }}
          ports:
            - name: http
              containerPort: 9998
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Xmx3g"
          resources:
            {{- toYaml .Values.tika.resources | nindent 12 }}
{{- end }}
