{{- if .Values.onlyoffice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
{{- end }}
