{{- include "ocis.basicServiceTemplates" (dict "scope" . "appName" "appNameWebfinger" "appNameSuffix" "") -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.affinity" .Values.services.webfinger | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- include "ocis.priorityClassName" $.priorityClassName | nindent 6 }}
      {{- include "ocis.hostAliases" $ | nindent 6 }}
      nodeSelector: {{ toYaml $.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["webfinger", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            {{- include "ocis.serviceRegistry" . | nindent 12 }}
            {{- include "ocis.cors" . |nindent 12 }}

            - name: WEBFINGER_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: WEBFINGER_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: WEBFINGER_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: WEBFINGER_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: WEBFINGER_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: WEBFINGER_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}

            - name: WEBFINGER_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: WEBFINGER_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: WEBFINGER_HTTP_ADDR
              value: 0.0.0.0:8080
            - name: WEBFINGER_DEBUG_ADDR
              value: 0.0.0.0:8081

            - name: WEBFINGER_OIDC_ISSUER
            {{- if not .Values.features.externalUserManagement.enabled }}
              value: "https://{{ .Values.externalDomain }}"
            {{- else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI | quote }}
            {{- end }}
            - name: WEBFINGER_OWNCLOUD_SERVER_INSTANCE_URL
              value: "https://{{ required "externalDomain needs to be set" .Values.externalDomain }}"
            - name: WEBFINGER_INSECURE
              value: "{{ .Values.insecure.oidcIdpInsecure }}"

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 8080
            - name: metrics-debug
              containerPort: 8081
      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
