{{- if and (not .Values.collabora.existingSecret) .Values.collabora.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-collabora
type: Opaque
stringData:
  username: {{ .Values.collabora.admin.username }}
  password: {{ .Values.collabora.admin.password }}
{{- end }}