apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wireguard-leader-election-rolebinding
  namespace: wireguard-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wireguard-leader-election-role
subjects:
  - kind: ServiceAccount
    name: wireguard-controller-manager
    namespace: wireguard-system
