{{- if and .Values.postgres.enabled .Values.keycloak.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.postgres.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
