{{- if and .Values.onlyoffice.enabled (or (eq .Values.ingress.annotationsPreset "traefik") (eq .Values.httpRoute.gateway.className "traefik")) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-x-forwarded-proto-https
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
{{- end}}
