{{- if .Values.keycloak.internal.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.keycloak.fullname" . }}-script
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
{{ (.Files.Glob "files/keycloak/*.sh").AsConfig | indent 2 }}
{{- end }}
