{{- if and (not .Values.keycloak.internal.existingSecret) .Values.keycloak.internal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.keycloak.fullname" . }}
type: Opaque
stringData:
  adminUser: {{ .Values.keycloak.internal.adminUser }}
  adminPassword: {{ .Values.keycloak.internal.adminPassword }}
{{- end }}