{{- if .Values.keycloak.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.keycloak.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}
