{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "twitch-predictions-recorder.serviceAccountName" . }}
  labels:
{{ include "twitch-predictions-recorder.labels" . | indent 4 }}
{{- end -}}
