{{- if and (not .Values.opencloud.smtp.existingSecret) .Values.opencloud.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-smtp
type: Opaque
stringData:
  smtpUser: {{ .Values.opencloud.smtp.username }}
  smtpPassword: {{ .Values.opencloud.smtp.password }}
{{- end }}
---
{{- if not .Values.opencloud.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}
type: Opaque
stringData:
  adminPassword: {{ .Values.opencloud.adminPassword }}
{{- end }}
---
{{- if and (eq .Values.opencloud.storage.mode "s3") (not .Values.opencloud.storage.s3.external.existingSecret) .Values.opencloud.storage.s3.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-s3
type: Opaque
stringData:
  accessKey: {{ .Values.opencloud.storage.s3.external.accessKey }}
  secretKey: {{ .Values.opencloud.storage.s3.external.secretKey }}
{{- end }}