{{- if and .Values.opencloud.enabled .Values.webExtensions.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-web-extensions-init
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
data:
  init-web-extensions.sh: |-
{{- (tpl (.Files.Get "files/opencloud/init-web-extensions.sh.gotmpl") . ) | nindent 4 }}
{{- end }}
